### ISSUE TITLE
error 15

### ISSUE THREAD

**Issue by THeavyGuy** [Spells-TF/issues-tracker#1]
When trying to purchase Spells  tf...
Genuine Foppish Physician
Die Job
3 keys, 0 ref
Error---
Trade Failed
Received EResult: 15.
Processing
Sending
Confirming
Close
Never had trouble before not sure but I think everything on my end is correct. Any help in this matter would be appreciated. Thank You.

**Comment by danocmx** [comment]
Steam related issue, closing.
